// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiAnalyzeAnalyzePostData, ApiAnalyzeAnalyzePostErrors, ApiAnalyzeAnalyzePostResponses, ApiListProjectsProjectsGetData, ApiListProjectsProjectsGetResponses, ApiPlanPlanPostData, ApiPlanPlanPostErrors, ApiPlanPlanPostResponses, ApiQueryQueryPostData, ApiQueryQueryPostErrors, ApiQueryQueryPostResponses, ApiScanScanPostData, ApiScanScanPostErrors, ApiScanScanPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Api Scan
 */
export const apiScanScanPost = <ThrowOnError extends boolean = false>(options: Options<ApiScanScanPostData, ThrowOnError>) => (options.client ?? client).post<ApiScanScanPostResponses, ApiScanScanPostErrors, ThrowOnError>({
    url: '/scan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Query
 */
export const apiQueryQueryPost = <ThrowOnError extends boolean = false>(options: Options<ApiQueryQueryPostData, ThrowOnError>) => (options.client ?? client).post<ApiQueryQueryPostResponses, ApiQueryQueryPostErrors, ThrowOnError>({
    url: '/query',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Analyze
 */
export const apiAnalyzeAnalyzePost = <ThrowOnError extends boolean = false>(options: Options<ApiAnalyzeAnalyzePostData, ThrowOnError>) => (options.client ?? client).post<ApiAnalyzeAnalyzePostResponses, ApiAnalyzeAnalyzePostErrors, ThrowOnError>({
    url: '/analyze',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Plan
 */
export const apiPlanPlanPost = <ThrowOnError extends boolean = false>(options: Options<ApiPlanPlanPostData, ThrowOnError>) => (options.client ?? client).post<ApiPlanPlanPostResponses, ApiPlanPlanPostErrors, ThrowOnError>({
    url: '/plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api List Projects
 *
 * List all available projects in PROJECTS_ROOT.
 * Returns project information including scan status and file counts.
 */
export const apiListProjectsProjectsGet = <ThrowOnError extends boolean = false>(options?: Options<ApiListProjectsProjectsGetData, ThrowOnError>) => (options?.client ?? client).get<ApiListProjectsProjectsGetResponses, unknown, ThrowOnError>({ url: '/projects', ...options });
