// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ApiAnalyzeAnalyzePostData, ApiAnalyzeAnalyzePostErrors, ApiAnalyzeAnalyzePostResponses, ApiListProjectsProjectsGetData, ApiListProjectsProjectsGetResponses, ApiPlanPlanPostData, ApiPlanPlanPostErrors, ApiPlanPlanPostResponses, ApiQueryQueryPostData, ApiQueryQueryPostErrors, ApiQueryQueryPostResponses, ApiScanScanPostData, ApiScanScanPostErrors, ApiScanScanPostResponses, DeepTraceAnalyzeDeepTraceAnalyzePostData, DeepTraceAnalyzeDeepTraceAnalyzePostErrors, DeepTraceAnalyzeDeepTraceAnalyzePostResponses, DeepTraceApplyDeepTraceApplyPostData, DeepTraceApplyDeepTraceApplyPostErrors, DeepTraceApplyDeepTraceApplyPostResponses, GetGraphGraphPostData, GetGraphGraphPostErrors, GetGraphGraphPostResponses, GetNodeDetailsNodeDetailsPostData, GetNodeDetailsNodeDetailsPostErrors, GetNodeDetailsNodeDetailsPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Api Scan
 */
export const apiScanScanPost = <ThrowOnError extends boolean = false>(options: Options<ApiScanScanPostData, ThrowOnError>) => (options.client ?? client).post<ApiScanScanPostResponses, ApiScanScanPostErrors, ThrowOnError>({
    url: '/scan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Query
 */
export const apiQueryQueryPost = <ThrowOnError extends boolean = false>(options: Options<ApiQueryQueryPostData, ThrowOnError>) => (options.client ?? client).post<ApiQueryQueryPostResponses, ApiQueryQueryPostErrors, ThrowOnError>({
    url: '/query',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Analyze
 */
export const apiAnalyzeAnalyzePost = <ThrowOnError extends boolean = false>(options: Options<ApiAnalyzeAnalyzePostData, ThrowOnError>) => (options.client ?? client).post<ApiAnalyzeAnalyzePostResponses, ApiAnalyzeAnalyzePostErrors, ThrowOnError>({
    url: '/analyze',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api Plan
 */
export const apiPlanPlanPost = <ThrowOnError extends boolean = false>(options: Options<ApiPlanPlanPostData, ThrowOnError>) => (options.client ?? client).post<ApiPlanPlanPostResponses, ApiPlanPlanPostErrors, ThrowOnError>({
    url: '/plan',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Graph
 *
 * Get graph data for visualization.
 * Returns nodes and edges in a format suitable for graph visualization libraries.
 */
export const getGraphGraphPost = <ThrowOnError extends boolean = false>(options: Options<GetGraphGraphPostData, ThrowOnError>) => (options.client ?? client).post<GetGraphGraphPostResponses, GetGraphGraphPostErrors, ThrowOnError>({
    url: '/graph',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deep Trace Analyze
 *
 * Analyzes a node for potential deep trace relationships.
 */
export const deepTraceAnalyzeDeepTraceAnalyzePost = <ThrowOnError extends boolean = false>(options: Options<DeepTraceAnalyzeDeepTraceAnalyzePostData, ThrowOnError>) => (options.client ?? client).post<DeepTraceAnalyzeDeepTraceAnalyzePostResponses, DeepTraceAnalyzeDeepTraceAnalyzePostErrors, ThrowOnError>({
    url: '/deep-trace/analyze',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deep Trace Apply
 *
 * Applies a deep trace relationship between two nodes.
 */
export const deepTraceApplyDeepTraceApplyPost = <ThrowOnError extends boolean = false>(options: Options<DeepTraceApplyDeepTraceApplyPostData, ThrowOnError>) => (options.client ?? client).post<DeepTraceApplyDeepTraceApplyPostResponses, DeepTraceApplyDeepTraceApplyPostErrors, ThrowOnError>({
    url: '/deep-trace/apply',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Node Details
 *
 * Gets comprehensive details for a node including source code, related nodes, and metadata.
 */
export const getNodeDetailsNodeDetailsPost = <ThrowOnError extends boolean = false>(options: Options<GetNodeDetailsNodeDetailsPostData, ThrowOnError>) => (options.client ?? client).post<GetNodeDetailsNodeDetailsPostResponses, GetNodeDetailsNodeDetailsPostErrors, ThrowOnError>({
    url: '/node/details',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Api List Projects
 *
 * List all available projects in PROJECTS_ROOT.
 * Returns project information including scan status and file counts.
 */
export const apiListProjectsProjectsGet = <ThrowOnError extends boolean = false>(options?: Options<ApiListProjectsProjectsGetData, ThrowOnError>) => (options?.client ?? client).get<ApiListProjectsProjectsGetResponses, unknown, ThrowOnError>({ url: '/projects', ...options });
