// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnalyzeRequest
 */
export type AnalyzeRequest = {
    /**
     * Task
     */
    task: string;
    /**
     * Path
     */
    path: string;
    /**
     * N
     */
    n?: number;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Prompt Template
     */
    prompt_template?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PlanRequest
 */
export type PlanRequest = {
    /**
     * Task
     */
    task: string;
    /**
     * Path
     */
    path: string;
    /**
     * N
     */
    n?: number;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Prompt Template
     */
    prompt_template?: string | null;
    /**
     * Format
     */
    format?: string | null;
};

/**
 * QueryRequest
 */
export type QueryRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Path
     */
    path: string;
    /**
     * N
     */
    n?: number;
    /**
     * With Graph
     */
    with_graph?: boolean;
    /**
     * Xml
     */
    xml?: boolean;
};

/**
 * ScanRequest
 */
export type ScanRequest = {
    /**
     * Path
     */
    path: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ApiScanScanPostData = {
    body: ScanRequest;
    path?: never;
    query?: never;
    url: '/scan';
};

export type ApiScanScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiScanScanPostError = ApiScanScanPostErrors[keyof ApiScanScanPostErrors];

export type ApiScanScanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiQueryQueryPostData = {
    body: QueryRequest;
    path?: never;
    query?: never;
    url: '/query';
};

export type ApiQueryQueryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiQueryQueryPostError = ApiQueryQueryPostErrors[keyof ApiQueryQueryPostErrors];

export type ApiQueryQueryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiAnalyzeAnalyzePostData = {
    body: AnalyzeRequest;
    path?: never;
    query?: never;
    url: '/analyze';
};

export type ApiAnalyzeAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiAnalyzeAnalyzePostError = ApiAnalyzeAnalyzePostErrors[keyof ApiAnalyzeAnalyzePostErrors];

export type ApiAnalyzeAnalyzePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiPlanPlanPostData = {
    body: PlanRequest;
    path?: never;
    query?: never;
    url: '/plan';
};

export type ApiPlanPlanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiPlanPlanPostError = ApiPlanPlanPostErrors[keyof ApiPlanPlanPostErrors];

export type ApiPlanPlanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiListProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ApiListProjectsProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
