// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnalyzeRequest
 */
export type AnalyzeRequest = {
    /**
     * Task
     */
    task: string;
    /**
     * Path
     */
    path: string;
    /**
     * N
     */
    n?: number;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Prompt Template
     */
    prompt_template?: string | null;
};

/**
 * DeepLinkCreateRequest
 */
export type DeepLinkCreateRequest = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Target Id
     */
    target_id: string;
    /**
     * Rel Type
     */
    rel_type: string;
    /**
     * Properties
     */
    properties?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DeepLinkDeleteRequest
 */
export type DeepLinkDeleteRequest = {
    /**
     * Relationship Id
     */
    relationship_id: string;
};

/**
 * DeepLinkSearchRequest
 */
export type DeepLinkSearchRequest = {
    /**
     * Query
     */
    query: string;
    /**
     * Project Root
     */
    project_root: string;
    /**
     * Limit
     */
    limit?: number;
};

/**
 * DeepTraceAnalyzeRequest
 */
export type DeepTraceAnalyzeRequest = {
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Project Root
     */
    project_root: string;
};

/**
 * DeepTraceApplyRequest
 */
export type DeepTraceApplyRequest = {
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Target Id
     */
    target_id: string;
    /**
     * Rel Type
     */
    rel_type: string;
};

/**
 * GraphRequest
 */
export type GraphRequest = {
    /**
     * Project Root
     */
    project_root: string;
    /**
     * File Paths
     */
    file_paths?: Array<string> | null;
    /**
     * Max Nodes
     */
    max_nodes?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NodeDetailsRequest
 */
export type NodeDetailsRequest = {
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Project Root
     */
    project_root: string;
};

/**
 * PlanRequest
 */
export type PlanRequest = {
    /**
     * Task
     */
    task: string;
    /**
     * Path
     */
    path: string;
    /**
     * N
     */
    n?: number;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Prompt Template
     */
    prompt_template?: string | null;
    /**
     * Format
     */
    format?: string | null;
};

/**
 * QueryRequest
 */
export type QueryRequest = {
    /**
     * Text
     */
    text: string;
    /**
     * Path
     */
    path: string;
    /**
     * N
     */
    n?: number;
    /**
     * With Graph
     */
    with_graph?: boolean;
    /**
     * Xml
     */
    xml?: boolean;
};

/**
 * ScanRequest
 */
export type ScanRequest = {
    /**
     * Path
     */
    path: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ApiScanScanPostData = {
    body: ScanRequest;
    path?: never;
    query?: never;
    url: '/scan';
};

export type ApiScanScanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiScanScanPostError = ApiScanScanPostErrors[keyof ApiScanScanPostErrors];

export type ApiScanScanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiQueryQueryPostData = {
    body: QueryRequest;
    path?: never;
    query?: never;
    url: '/query';
};

export type ApiQueryQueryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiQueryQueryPostError = ApiQueryQueryPostErrors[keyof ApiQueryQueryPostErrors];

export type ApiQueryQueryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiAnalyzeAnalyzePostData = {
    body: AnalyzeRequest;
    path?: never;
    query?: never;
    url: '/analyze';
};

export type ApiAnalyzeAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiAnalyzeAnalyzePostError = ApiAnalyzeAnalyzePostErrors[keyof ApiAnalyzeAnalyzePostErrors];

export type ApiAnalyzeAnalyzePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiPlanPlanPostData = {
    body: PlanRequest;
    path?: never;
    query?: never;
    url: '/plan';
};

export type ApiPlanPlanPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiPlanPlanPostError = ApiPlanPlanPostErrors[keyof ApiPlanPlanPostErrors];

export type ApiPlanPlanPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGraphGraphPostData = {
    body: GraphRequest;
    path?: never;
    query?: never;
    url: '/graph';
};

export type GetGraphGraphPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGraphGraphPostError = GetGraphGraphPostErrors[keyof GetGraphGraphPostErrors];

export type GetGraphGraphPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeepTraceAnalyzeDeepTraceAnalyzePostData = {
    body: DeepTraceAnalyzeRequest;
    path?: never;
    query?: never;
    url: '/deep-trace/analyze';
};

export type DeepTraceAnalyzeDeepTraceAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeepTraceAnalyzeDeepTraceAnalyzePostError = DeepTraceAnalyzeDeepTraceAnalyzePostErrors[keyof DeepTraceAnalyzeDeepTraceAnalyzePostErrors];

export type DeepTraceAnalyzeDeepTraceAnalyzePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeepTraceApplyDeepTraceApplyPostData = {
    body: DeepTraceApplyRequest;
    path?: never;
    query?: never;
    url: '/deep-trace/apply';
};

export type DeepTraceApplyDeepTraceApplyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeepTraceApplyDeepTraceApplyPostError = DeepTraceApplyDeepTraceApplyPostErrors[keyof DeepTraceApplyDeepTraceApplyPostErrors];

export type DeepTraceApplyDeepTraceApplyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetNodeDetailsNodeDetailsPostData = {
    body: NodeDetailsRequest;
    path?: never;
    query?: never;
    url: '/node/details';
};

export type GetNodeDetailsNodeDetailsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNodeDetailsNodeDetailsPostError = GetNodeDetailsNodeDetailsPostErrors[keyof GetNodeDetailsNodeDetailsPostErrors];

export type GetNodeDetailsNodeDetailsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeepLinkSearchDeepLinkSearchPostData = {
    body: DeepLinkSearchRequest;
    path?: never;
    query?: never;
    url: '/deep-link/search';
};

export type DeepLinkSearchDeepLinkSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeepLinkSearchDeepLinkSearchPostError = DeepLinkSearchDeepLinkSearchPostErrors[keyof DeepLinkSearchDeepLinkSearchPostErrors];

export type DeepLinkSearchDeepLinkSearchPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeepLinkCreateDeepLinkCreatePostData = {
    body: DeepLinkCreateRequest;
    path?: never;
    query?: never;
    url: '/deep-link/create';
};

export type DeepLinkCreateDeepLinkCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeepLinkCreateDeepLinkCreatePostError = DeepLinkCreateDeepLinkCreatePostErrors[keyof DeepLinkCreateDeepLinkCreatePostErrors];

export type DeepLinkCreateDeepLinkCreatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeepLinkListDeepLinkListPostData = {
    body: NodeDetailsRequest;
    path?: never;
    query?: never;
    url: '/deep-link/list';
};

export type DeepLinkListDeepLinkListPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeepLinkListDeepLinkListPostError = DeepLinkListDeepLinkListPostErrors[keyof DeepLinkListDeepLinkListPostErrors];

export type DeepLinkListDeepLinkListPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeepLinkDeleteDeepLinkDeletePostData = {
    body: DeepLinkDeleteRequest;
    path?: never;
    query?: never;
    url: '/deep-link/delete';
};

export type DeepLinkDeleteDeepLinkDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeepLinkDeleteDeepLinkDeletePostError = DeepLinkDeleteDeepLinkDeletePostErrors[keyof DeepLinkDeleteDeepLinkDeletePostErrors];

export type DeepLinkDeleteDeepLinkDeletePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApiListProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ApiListProjectsProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
